version: '3.7'

services:
  mysql-service:
    image: mysql:8.0.20
    networks:
      - mobilab-network
    volumes:
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
  account-manager-service:
    container_name: account-manager-service
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - mobilab-network
    depends_on:
      - mysql-service
    environment:
      - DATABASE_HOST=mysql-service
      - DATABASE_PORT=3306
      - WAIT_HOSTS=mysql-service:3306
networks:
  mobilab-network:
    driver: bridge
