spring:
  application:
    name: accountmanager
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      connection-test-query: select 1 from dual
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:mysql://mysql-service:${DATABASE_PORT:3307}/mysql?useSSL=false&allowPublicKeyRetrieval=true
    jdbcUrl: jdbc:mysql://mysql-service:${DATABASE_PORT:3307}/mysql?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
